services:

  postgres:
    image: postgres:16-alpine
    container_name: ecommerce-prod-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: ecommerce-prod-api
    environment:
      NODE_ENV: production
      PORT: 4000
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
      FRONTEND_LOCAL_URL: ${FRONTEND_LOCAL_URL}
    ports:
      - "4000:4000"
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - postgres
    restart: unless-stopped

  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: ecommerce-prod-nextjs
    environment:
      NODE_ENV: production
      API_URL: http://api:4000
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: ecommerce-prod-tunnel
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - nextjs
      - api
    restart: unless-stopped

  adminer:
    image: adminer:latest
    container_name: ecommerce-prod-adminer
    ports:
      - "${IP_LOCAL}:8000:8080"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_prod_data:
