services:

  postgres:
    image: postgres:16-alpine
    container_name: ecommerce-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  adminer:
    image: adminer:latest
    container_name: ecommerce-adminer
    ports:
      - "8000:8080"
    depends_on:
      - postgres
    restart: unless-stopped

  api:
    build:
      context: ./backend
    container_name: ecommerce-api
    environment:
      PORT: 4000
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      IFTHENPAY_MBWAY_KEY: ${IFTHENPAY_MBWAY_KEY}
      IFTHENPAY_CALLBACK_KEY: ${IFTHENPAY_CALLBACK_KEY}
    volumes:
      - ./backend/src:/app/src
      - ./backend/prisma:/app/prisma
      - ./backend/uploads:/app/uploads
      - ./backend/data:/app/data
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    restart: unless-stopped

  nextjs:
    build:
      context: ./frontend
    container_name: ecommerce-nextjs
    environment:
      API_URL: http://api:4000
      NEXT_PUBLIC_API_URL: http://${IP_LOCAL}:4000
      WATCHPACK_POLLING: "true"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  postgres_data: